### ISSUE TITLE
Drawing of NeoVim UI elements gets messed up until the window is resized

### ISSUE THREAD

**Issue by YorickPeterse** [Lyude/neovim-gtk#13]
**Describe the bug**

When opening neovim-gtk, certain elements such as the tab bar seem to not get rendered properly when using NeoVim's own elements. This can be seen here:

https://user-images.githubusercontent.com/86065/145731475-1993815b-af85-45bd-b0c2-04db777a2854.mp4

I'm using the following neovim-gtk settings:

```vim
set mouse=a
set mousemodel=popup

if exists('g:GtkGuiLoaded')
  call rpcnotify(1, 'Gui', 'Font', 'Source code Pro 8')
  call rpcnotify(1, 'Gui', 'Linespace', '0')
  call rpcnotify(1, 'Gui', 'Option', 'Popupmenu', 0)
  call rpcnotify(1, 'Gui', 'Option', 'Tabline', 0)
  call rpcnotify(1, 'Gui', 'Command', 'SetCursorBlink', '0')
end
```

**Technical information (please complete the following information):**
 - OS: Arch Linux
 - Neovim version: 0.6.0
 - Neovim-Gtk build version: v0.2.0-144-g1f0628a (built from `master`)
 - Gnome 41.2 with Wayland

**Comment by jacobmischka** [comment]
Ha yeah, this has been an issue for quite a while: https://github.com/daa84/neovim-gtk/issues/49

**Comment by YorickPeterse** [comment]
I'm no longer experiencing this using the new GTK4 version.
