### ISSUE TITLE
Background white when loading immediately after launching

### ISSUE THREAD

**Issue by jacobmischka** [Lyude/neovim-gtk#21]
As of 0.4.0, the main window is always black on white before initialization is finished. ~~Prior to this version, it would immediately launch with my colorscheme.~~ It does load eventually, so this isn't a huge deal, but it's a bit jarring to see the bright white window for a few ms now.

https://user-images.githubusercontent.com/3939997/150674606-50f34d4f-eba8-42b5-9afc-866c97ed2b13.mp4

**Technical information (please complete the following information):**
 - OS: Arch Linux
 - Neovim version: 0.6.1
 - Neovim-Gtk build version: 0.4.0 (976693e33071efc3e3e5701cb03ed4eee8dad7f7)

**Comment by jacobmischka** [comment]
Hm. I could have sworn that the colors were correct immediately, but maybe I was wrong. I'll have to investigate more on my other computer tomorrow which I haven't updated yet, because I can't seem to find a commit now that behaves as I remember.

 At the very least, the default change from dark background to light in f0d9019a31c64092e690d3ff9b611013f2500a4a is noticeable. There's not necessarily a "correct" assumption between light and dark as a default, though dark seems to have been the previous behavior and seems more likely for neovim users.

**Comment by Lyude** [comment]
> Hm. I could have sworn that the colors were correct immediately, but maybe I was wrong. I'll have to investigate more on my other computer tomorrow which I haven't updated yet, because I can't seem to find a commit now that behaves as I remember.
> 
> At the very least, the [default change from dark background to light](https://github.com/Lyude/neovim-gtk/commit/f0d9019a31c64092e690d3ff9b611013f2500a4a#diff-9df84bc451a5211110d67dd9b47c627ded197d37c6e04e38b5a8d0fe098257d3R39) in [f0d9019](https://github.com/Lyude/neovim-gtk/commit/f0d9019a31c64092e690d3ff9b611013f2500a4a) is noticeable.
> 
> There's not necessarily a "correct" assumption between light and dark as a default, though dark seems to have been the previous behavior and seems more likely for neovim users.

Mhh - I didn't even think about this when changing it, as I generally run with solarized. It would probably be good to make sure as well that it's actually still on the default color when initialized and that the autocmd we execute when starting up to read the initial `background` state hasn't been executed yet. With that being said though, I'm happy to switch the default back to dark - I think most people would prefer that, and it would be better to maintain the previous behavior we had. I should note though, I've been considering replacing the loading screen when I start coming up with a `DrawingArea` replacement for #8, so in the future we may simply do something like display a spinner against the system theme's background and not use the nvim colors there.

**Comment by jacobmischka** [comment]
:+1:

>  I could have sworn that the colors were correct immediately, but maybe I was wrong. I'll have to investigate more on my other computer tomorrow which I haven't updated yet, because I can't seem to find a commit now that behaves as I remember.

I was misremembering (vividly!) because it was just black-on-white before. Appreciate the swap!
