### ISSUE TITLE
Option as Meta on macOS

### ISSUE THREAD

**Issue by jacobmischka** [Lyude/neovim-gtk#23]
I recently started using a macbook for work, and I can't seem to trick macOS into treating the `option` key as `meta` globally. It seems the convention on this OS is for apps to have to override this manually:

- https://support.apple.com/guide/terminal/change-profiles-keyboard-preferences-trmlkbrd/mac
- https://youtrack.jetbrains.com/issue/IDEA-165184
- https://github.com/microsoft/vscode/issues/11314

I would like to use the same setup that I'm accustomed to on Linux with nvim-gtk and some meta keybindings, but I can't get that to work now. I'm very unfamiliar with macOS, so it's possible I'm doing something wrong, but I think we have to do some special handling in the app to get this to work? Will try looking into this soon.

**Comment by Lyude** [comment]
My roommates have macbooks so I may actually be able to look into this locally, but I also have no experience with OSX dev so I figured I'd add a help wanted label anyway :).
Will also ask the folks in the GTK IRC about this to see if they have any idea what might be going on. Although, I do wonder if maybe we just need to tell nvim to pretend Option is meta…

**Comment by jacobmischka** [comment]
It looks like vscode's xterm library manually intercepts and sends `ESC` + the optionless keycode, which is what iTerm2's option text says as well (though I haven't looked at its source code):

https://github.com/xtermjs/xterm.js/blob/cb3dd19039732e8a6e2a0ed594cdad1448ff8084/src/common/input/Keyboard.ts#L350-L371

Would be nice if there were some built-in way in GTK to do this, but if there is I haven't found it in a few hours of searching.
