### ISSUE TITLE
Integrated clipboard support fails with “Function name does not match script file name: provider#clipboard#Call”

### ISSUE THREAD

**Issue by Hawk777** [Lyude/neovim-gtk#36]
**Describe the bug**
If I start `nvim-gtk` normally, everything is fine. As soon as I add `let g:GuiInternalClipboard=1` to `init.vim`, I get a failure to initialize `[2022-10-22T20:43:56Z ERROR nvim_gtk::error] Can't initialize nvim: Elapsed(())`. If I run `nvim` directly as `nvim --cmd 'set termguicolors' --cmd 'let g:GtkGuiLoaded = 1' --cmd "let &rtp.=',/usr/share/nvim-gtk/runtime'"` (i.e. the same options that it was run with by `nvim-gtk`, except for `--embed`), I get the the error named in the bug title while processing `nvim_gui_shim.vim`.

I originally reported this [here](https://github.com/daa84/neovim-gtk/issues/245) but it was never addressed so I’m moving it to this fork, as this seems to be where continuing development is happening.

**Technical information (please complete the following information):**
 - OS: Gentoo Linux
 - Neovim version: 0.7.2
 - Neovim-Gtk build version: 0.4.1 release

**Comment by Lyude** [comment]
This is only sort of a bug. _Technically_ a neovim GUI should be configurable from init.vim, but `nvim-gtk`'s startup sequence has been a bit of a mess since before I started working on this, and we make the mistake of not setting global options we want to be available to init.vim before caling `nvim_ui_attach()`. They actually mention `ginit.vim` on the wiki page you mention in the original bug for this exact reason, and if you put your options in there then things should work as expected.

I'm going to mark this as a feature for the time being and rename this issue to reflect the actual problem here, but this is something I'd definitely like to get fixed at some point in the near future.

**Comment by Hawk777** [comment]
Hm, something doesn’t seem to be working there either. I deleted all the clipboard-related stuff from `init.vim` and added one line in `~/.config/nvim/ginit.vim` instead which is `let g:GuiInternalClipboard = 1` (which is all [the wiki page](https://github.com/daa84/neovim-gtk/wiki/Configuration#clipboard) seems to say I should need), but when I do `:%y *`, I get `clipboard: No provider. Try ":checkhealth" or ":h clipboard"`. `:checkhealth` says `WARNING: No clipboard tool found. Clipboard registers ("+ and "*) will not work.`.

Am I misunderstanding the wiki page? It sounds as if it’s saying just adding that one line to `ginit.vim` should do the job, but it doesn’t seem to in practice. This is with neovim-gtk 1.0.1 and neovim 0.8.1.

**Comment by Lyude** [comment]
> Hm, something doesn’t seem to be working there either. I deleted all the clipboard-related stuff from `init.vim` and added one line in `~/.config/nvim/ginit.vim` instead which is `let g:GuiInternalClipboard = 1` (which is all [the wiki page](https://github.com/daa84/neovim-gtk/wiki/Configuration#clipboard) seems to say I should need), but when I do `:%y *`, I get `clipboard: No provider. Try ":checkhealth" or ":h clipboard"`. `:checkhealth` says `WARNING: No clipboard tool found. Clipboard registers ("+ and "*) will not work.`.
> 
> Am I misunderstanding the wiki page? It sounds as if it’s saying just adding that one line to `ginit.vim` should do the job, but it doesn’t seem to in practice. This is with neovim-gtk 1.0.1 and neovim 0.8.1.

It totally might have just broken at some point and I didn't notice, there has been a lot of code churn. I would like to fix the init.vim option thing still, but I'll take a look at this more closely since it sounds like something else might be happening here
