### ISSUE TITLE
Underdot rendering seems too close to line/too large

### ISSUE THREAD

**Issue by jacobmischka** [Lyude/neovim-gtk#43]
I'm having difficulty reading text behind/above the underdots, they seem too close to the baseline and a bit too large to me. Particularly it's hard to read words with underscores or descenders underneath the dots.

![image](https://user-images.githubusercontent.com/3939997/208272448-dde847ca-14cc-451f-982f-e5f9e60b23ea.png)

I've played around with a few somewhat magical/random adjustments that feel better for me, but admittedly I'm unsure how this looks with other fonts/sizes.

Both changes are visible in this screenshot (`diameter` was reduced by `underline_thickness` and `y` was increased by `diameter`). I'm happy to make a PR, possibly with other adjustments, if desired.

![image](https://user-images.githubusercontent.com/3939997/208272465-335d90df-62fc-439c-90b3-3259d8c5f76e.png)

---

Somewhat unrelated: does this project not use rustfmt/cargo fmt any longer? I saved the file and a lot of formatting things changed when rustfmt formatted it.

**Comment by jacobmischka** [comment]
Actually, after a bit more fiddling maybe just reducing the dot size is enough, it is a bit too low after adjusting `y` as I did above. This is just with the `diameter` change:

![image](https://user-images.githubusercontent.com/3939997/208274278-e3d6d86c-94c9-47b8-898c-3bef6e433b67.png)

Anyway, neither of these are perfect, but I find them both more usable than the large dots.

**Comment by Lyude** [comment]
> Somewhat unrelated: does this project not use rustfmt/cargo fmt any longer? I saved the file and a lot of formatting things changed when rustfmt formatted it.

JFYI: Not at the moment, but I'll try to fix this soon because it didn't even occur to me that people would be running rustfmt by default. The only reason I wasn't using it before was because iirc when I took over the repo originally and tried running it, there was already quite a lot of code that would get reformatted as-is. I think I tried to set it up, wasn't happy with whatever settings were in there and forgot about it until now.

**Comment by Lyude** [comment]
> Actually, after a bit more fiddling maybe just reducing the dot size is enough, it is a bit too low after adjusting `y` as I did above. This is just with the `diameter` change:
> 
> ![image](https://user-images.githubusercontent.com/3939997/208274278-e3d6d86c-94c9-47b8-898c-3bef6e433b67.png)
> 
> Anyway, neither of these are perfect, but I find them both more usable than the large dots.

That's to be expected - GTK+ does subpixel rendering now, and since many times the radius of the dot is going to not be a whole number of pixels there's some inconsistencies with how it gets scaled down on small resolutions.

Honestly I think the change you came up with looks nicer then what I had, feel free to open a PR!

**Comment by jacobmischka** [comment]
Sounds good! I'm going to use it for a little while before doing so I think, I'm not yet very happy with it either. I'll either submit a PR once I've come up with something that seems better, or close this in a little while if I'm unable to. Thanks!

**Comment by Lyude** [comment]
No problem, btw I forgot to mention: there is actually a neovim option called `linespace` that lets you adjust the number of pixel rows between each line of text. That should work I think. If not though I'd look through daa84's wiki to see if there's some RPC call there you can use to configure it, and let me know if that's the case so I can hook up the standard optjon. I'm not at my machine right now, but I've definitely had to touch code around this option today :P

**Comment by Lyude** [comment]
> > Somewhat unrelated: does this project not use rustfmt/cargo fmt any longer? I saved the file and a lot of formatting things changed when rustfmt formatted it.
> 
> JFYI: Not at the moment, but I'll try to fix this soon because it didn't even occur to me that people would be running rustfmt by default. The only reason I wasn't using it before was because iirc when I took over the repo originally and tried running it, there was already quite a lot of code that would get reformatted as-is. I think I tried to set it up, wasn't happy with whatever settings were in there and forgot about it until now.
> 
> Edit: Same for clippy.

also JFYI: `rustfmt` is good to go since 9ce66d9c3412dcaef0b90872a847d1fac997af22, and I just ran it on everything. Also added a `CONTRIBUTING.md`

**Comment by jacobmischka** [comment]
I'm going to close this for now, I've grown used to the larger dots. The smaller ones looked nice in isolation but were easy to lose when actually editing files. Thanks for entertaining my musings (and getting rustfmt set up again)!
