### ISSUE TITLE
Dotted underline instead of curly one for diagnostics

### ISSUE THREAD

**Issue by baco** [Lyude/neovim-gtk#47]
The curly undeline style on the GTK client doesn't have the same style as when running Neovim in a standalone terminal.

Terminal:
![Screenshot from 2022-12-20 21-07-09](https://user-images.githubusercontent.com/102958/208790587-4d9f992e-dba4-4b89-aa55-b69fc07dfe1d.png)

GTK4 UI:
![Screenshot from 2022-12-20 21-07-48](https://user-images.githubusercontent.com/102958/208790622-2d92c4e3-8347-4ac2-a654-9e0b5424a904.png)

In the GTK4 version the curly underline seems to be a dotted line rather than a curly wave.

**Technical information:**
 - OS: Debian testing
 - Neovim version: v0.9.0-dev-530+gde90a8bfe (Nightly release)
 - Neovim-Gtk build version: Compiled from source at commit v1.0.1

**Comment by jacobmischka** [comment]
#11
