### ISSUE TITLE
Cargo lockfile out of sync for v1.0.2

### ISSUE THREAD

**Issue by alerque** [Lyude/neovim-gtk#58]
The `Cargo.lock` file is out of sync for the tagged v1.0.2 release. This makes it difficult for distro packagers to create reproducible builds.

Please update it to match the `Cargo.toml` file before future releases and if possible do something so the release workflow doesn't miss this ;-)

**Comment by Lyude** [comment]
Whoops! Sorry about that, will fix it right away

**Comment by Lyude** [comment]
Fixed in v1.0.3
