### ISSUE TITLE
GTK+4 Support

### ISSUE THREAD

**Issue by Lyude** [Lyude/neovim-gtk#8]
Just a placeholder issue to let people know that I'm currently working on GTK+4 support for neovim-gtk. [~~Very broken WIP~~Basically working branch](https://github.com/Lyude/neovim-gtk/tree/gtk4)

# Current TODO

This list is is also a WIP, as I go through and figure out all of the things that need to be done. Sources:

- [GTK3 to 4 migration guide](https://docs.gtk.org/gtk4/migrating-3to4.html)

- [x] Possibly come up with a slower but less complicated port of our DrawingArea code to GTK4 that doesn't reuse previous surface content, so we have something to get things running in GTK4 in the interim of the conversion.
- [x] Once we have a simple DrawingArea port, come up with a custom widget replacement for it which does reuse previous surface content, and performs it's rendering through a `GtkSnapshot`.
- [x] [Adjust to focus handling changes](https://docs.gtk.org/gtk4/migrating-3to4.html#focus-handling-changes)
- [x] Stop using context menus
- [x] Adjust to popover positioning changes for file browser
- [x] Address TODO comments
- [x] [Adapt to icon sizing api changes](https://docs.gtk.org/gtk4/migrating-3to4.html#adapt-to-icon-size-api-changes)
- [x] Use `hexpand`/`vexpand` to fix widget packing
- [x] Get rid of `GtkWidgetExt::observe_children()` calls
- [x] Fix regression with nvim-lsp popups + native completion (current theory: `vim.o.columns` appears to be set incorrectly at start, perhaps we're attaching the UI before the window has been given a sane size?)

---

# DrawingArea replacement notes

Basically: `DrawingArea::queue_draw_area` was removed due to significant changes in the GTK4 drawing API, and according to GTK+ devs GTK4 isn't concerned about surface damage in this regard, as it has it's own mechanisms that it uses through `GtkSnapshot` nodes to do a better job of keeping track of damage regions in a way that makes more sense for HW accel. This means there's no functional equivalent to `DrawingArea::queue_draw_area`, and according to them the easiest alternative solution would be to come up with our own widget using `GtkSnapshot`. Maybe we can fit some fun hw accel tricks tricks with the new API when we do this!

---

# NvimViewport to-do

`NvimViewport` is the new widget I've come up with to replace `DrawingArea` that handles rendering the nvim grid entirely using GTK+ snapshots. It's far enough now it actually displays something!

- [x] Ensure `bg_alpha` works (should be done, just needs testing
- [x] Ensure `filled_alpha` works
- [x] Fix focus handling (needs to work on widget defocus and window defocus)
- [x] See if we can fix this weird thing ![image](https://user-images.githubusercontent.com/1527057/172065667-cfb73a16-dcf7-4cb8-9cfd-d1ad8a4d5b8e.png)
- [x] Cache grid state to be reused when blinking the cursor while nothing else on the screen has changed
- [x] ~Decide what to do with the external cmdline: port it to `NvimViewport`, or just get rid of it [1]~ Added `CmdlineViewport` widget
- [x] Get rid of most (all?) of the `InkOverflow` logic, it's no longer necessary in GTK4 as Snapshots will take care of tracking this for us - keeping it around just results in recreating `gsk::TextNode`s that don't need to be remade.
- [x] Come up with solution for cursor. I couldn't manage to get an XOR shader that looked nice enough under any given text color, so I came up with an alternative using the default background color
- [x] Come up with a solution for undercurl rendering
- [x] Get resizing to work
- [x] Optimize render node generation for drawing backgrounds across a line
- [x] Optimize render node generation for drawing strikethroughs, underlines and undercurls
- [x] Fix cursor rendering when out of focus
- [x] Fix resizing issues with `CmdlineViewport`

---

# Nice to have to-do (none of these got done, I just am pushing them off to a later release

- Consider coming up with a way of drawing undercurls in the style of GTK3? Do I care?
- See if it's worth caching lists of like-render nodes across each line?
- Clean up `f32`/`f64` mess w/ pango metrics
- Get rid of `TreeView`s.
- [Get rid of unneeded `GtkWidget::show()` calls and `visible` property changes](https://docs.gtk.org/gtk4/migrating-3to4.html#widgets-are-now-visible-by-default)

---

# Footnotes

1. ~~Considering it's not enabled by default and it's rather, strange, I kind of doubt anyone is actually using this option. As well, it's very likely I'm going to want to implement an external cmdline that emulates nvim's cmdline's appearance and doesn't actually look like a separate widget. The reason for wanting to implement this is that `ext_cmdline` must be implemented to allow for implementing an external message buffer - and we can use this to make things slightly more efficient without changing user's setups.~~ wasn't hard to implement

**Comment by Lyude** [comment]
Hi! A status update on this: Most of the work for GTK4 is done at this point (except for some minor tidbits, along with fixing up the plugin integration). My main focus ATM is on getting us moved over to a snapshot based widget for nvim's viewport. Just in case anyone was worried I forgot about this project :)

**Comment by sramkrishna** [comment]
Eager to see a GTK4 frontend to GNOME!

**Comment by Lyude** [comment]
Update: We have a fully functional snapshot widget now! I'm currently working now on trying to make it a lot more efficient, since currently we generate wayyyy more render nodes then we need to, and I'd like to at least make sure things are mostly on-par with gtk3 performance wise

**Comment by sramkrishna** [comment]
That's wonderful news! Feel free to join the GNOME channels for any advice
or tips. Tell them 'sri' sent you. :)

**Comment by Lyude** [comment]
Little status update: completion menu moved over to using GtkListView. GtkListView is, more broken then I'd like on GTK+'s side. Scrolling -really- needs to get fixed with large lists of items, even though that's not an easy ask it's also not an easy ask for users to be expected to have to scroll random widgets with their keyboards rather then mouse cursors << (please feel free to bug GTK+ people to move this forward! it's, a bit upsetting lmao). Luckily though this only really seems to happen with _very_ large completion lists, and most of the time users are just going to be navigating things with their keyboard so it should be fine. Probably going to leave all of the other GtkListView candidates unconverted until GtkListView actually stabilizes.

Also, made a lot of progress figuring out why nvim-cmp has been so bizarre with documentation windows. I have a theory on what we're doing differently in GTK4 to cause this but haven't confirmed yet, at the very least though I have a workaround. Which means the GTK4 port is actually far enough for me to start dog fooding and use over the GTK3 version!

**Comment by Lyude** [comment]
oh! looks like they finally made plans to get this fixed by 4.10, so nevermind :). this bug should get fixed eventually it seems!

**Comment by Lyude** [comment]
Probably going to be releasing this pretty soon on the main branch! Was going to do bug fixes on the gtk3 version beforehand but I haven't been able to get the motivation, and honestly there's a lot of nice fixes this branch comes with anyhow :)

**Comment by YorickPeterse** [comment]
@Lyude Great to see progress being made towards GTK4! I've tried the gtk4 branch on and off over the last few weeks, though two glitches prevented me from really using it:

- The window titlebar text was white instead of black
- Sometimes `winbar` wouldn't show up. I'm guessing this was a similar issue to https://github.com/Lyude/neovim-gtk/issues/13

I tried again yesterday and it seems these issues have been resolved. I'll continue using it this week to see if any new issues pop up. Thanks for the hard work! :tada: :smile:

**Comment by Lyude** [comment]
JFYI I was going to be releasing it today but I found some lingering issues with the popup menu that I'm still figuring out which didn't show up until I upgraded my system to a more recent version of fedora. I should be very close now though :)

**Comment by YorickPeterse** [comment]
I think I found a bug in the GTK4 branch: if you open a neovim terminal (`:term`) and run `head -n 100 /dev/random`, the editor crashes. I'm guessing neovim-gtk tries to render something as text but fails, and crashes instead of handling it gracefully.

**Comment by Lyude** [comment]
> I think I found a bug in the GTK4 branch: if you open a neovim terminal (`:term`) and run `head -n 100 /dev/random`, the editor crashes. I'm guessing neovim-gtk tries to render something as text but fails, and crashes instead of handling it gracefully.

lmao, that's both clever and explains some random crashes I managed to hit in the last day or two that I couldn't seem to reproduce. Will make sure to fix this

**Comment by Lyude** [comment]
@YorickPeterse f048109 should fix this, although I suspect we might want to eventually come up with something to draw replacement glyphs? (🤷)
