### ISSUE TITLE
`unknown attribute fg_indexed` and `bg_indexed`

### ISSUE THREAD

**Issue by sdroege** [Lyude/neovim-gtk#86]
**Describe the bug**

```
[2023-02-05T15:56:17Z ERROR nvim_gtk::highlight] unknown attribute fg_indexed
[2023-02-05T15:56:17Z ERROR nvim_gtk::highlight] unknown attribute bg_indexed
```

This seems to come from the `fzf` plugin and is probably just a different kind of text highlighting?

I assume

**Technical information (please complete the following information):**
 - OS: Linux/Fedora 37
 - Neovim version: 0.8.2
 - Neovim-Gtk build version: latest git as of today

**Comment by sdroege** [comment]
I'm currently using the following

```diff
diff --git a/src/highlight.rs b/src/highlight.rs
index d20837a..f65ebe9 100644
--- a/src/highlight.rs
+++ b/src/highlight.rs
@@ -323,6 +323,7 @@ impl Highlight {
                 "underdashed" => model_attrs.underdashed = true,
                 "strikethrough" => model_attrs.strikethrough = true,
                 "blend" => (),
+                "fg_indexed" | "bg_indexed" => (),
                 attr_key => error!("unknown attribute {}", attr_key),
             };
         }
```

Not sure how it's supposed to look like. In `nvim` on the terminal there is no special highlighting either.

**Comment by Lyude** [comment]
> I'm currently using the following
> 
> ```diff
> diff --git a/src/highlight.rs b/src/highlight.rs
> index d20837a..f65ebe9 100644
> --- a/src/highlight.rs
> +++ b/src/highlight.rs
> @@ -323,6 +323,7 @@ impl Highlight {
>                  "underdashed" => model_attrs.underdashed = true,
>                  "strikethrough" => model_attrs.strikethrough = true,
>                  "blend" => (),
> +                "fg_indexed" | "bg_indexed" => (),
>                  attr_key => error!("unknown attribute {}", attr_key),
>              };
>          }
> ```
> 
> Not sure how it's supposed to look like. In `nvim` on the terminal there is no special highlighting either.

I think this is probably a good fix, provided we leave a `// TODO:` comment of some sort… I think?

The problem is I can't actually seem to figure out what on earth `fg_indexed` and `bg_indexed` are for in the first place? They don't seem to be documented in any of the nvim documentation I've read through…

**Comment by sdroege** [comment]
The best I can find is https://github.com/glacambre/nwin/commit/2b151175282c99b9480790ed4d68a50ab2803350 and https://github.com/search?q=fg_indexed&type=code
